### ISSUE TITLE
regarding redis-cli

### ISSUE THREAD

**Issue by mkscala** [sickp/docker-alpine-redis#1]
I am using your image.
I wanted 1 Generic Redis Server Container and then 'N' number of Redis-CLI Container(where only the redis cli tools)
Once Redis Server Container 
Every time when i run docker-compose run rcli, I wanted only the redis-cli container to get created 

  image: sickp/alpine-redis:3.2.0 
  links:
    - redis
  command: redis-cli -h redis

I wanted to call the below command from the webapp
docker-compose run rcli

**Comment by sickp** [comment]
The default `/etc/redis.conf` changed in 3.2.0 to explicitly `bind 127.0.0.1`, that is, the configuration only allowed localhost connections, so `redis-cli -h redis` failed.

I've updated the images to explicitly `bind 0.0.0.0` which effectively disables this protection, and allows other containers on the same network to connect. Docker networks provide isolation for us.

**Comment by mkscala** [comment]
How does your docker-compose file look ? Do you have 2 containers spin up? Please let me know.
1 for redis-server and 1 just with redis-tools(without redis-sever)

**Comment by sickp** [comment]
This connects `redis-cli` to the redis server and executes the `info` command:

```yaml
version: '2'
services:
  redis-cli:
    command: redis-cli -h myserver info
    image: sickp/alpine-redis:3.2.0
  redis:
    container_name: myserver
    image: sickp/alpine-redis:3.2.0
```
